import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geist", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      colors: {
        void: "#020408",
        obsidian: "#080D14",
        surface: "#0C1118",
        "surface-2": "#111820",
        "surface-3": "#161F2A",
        "border-dim": "#1A2535",
        "border-default": "#1F2E42",
        "border-bright": "#2A3F5C",
        "text-primary": "#E8EFF8",
        "text-secondary": "#7A8FA6",
        "text-tertiary": "#3D5270",
        "text-accent": "#4D9FFF",
        "glow-blue": "#0066FF",
        "glow-cyan": "#00C2FF",
        "glow-purple": "#7C3AED",
        "glow-emerald": "#00C896",
        background: "#020408",
        foreground: "#E8EFF8",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        verdict: {
          verified: "#00C896",
          "verified-dim": "#001F16",
          disputed: "#F5A623",
          "disputed-dim": "#1F1400",
          false: "#FF3B5C",
          "false-dim": "#200010",
          unsupported: "#4D6680",
          "unsupported-dim": "#0A1018",
          insufficient: "#4D9FFF",
          "insufficient-dim": "#00101F",
        },
        tier: {
          1: "#00C896",
          2: "#4D9FFF",
          3: "#F5A623",
          4: "#4D6680",
        },
        manipulation: "#FF6B35",
        "manipulation-dim": "#1A0A00",
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-slow": "float 9s ease-in-out infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        shimmer: "shimmer 1.5s ease infinite",
        "spin-slow": "spin 8s linear infinite",
        "ping-once": "ping 0.6s ease-out 1",
        "fade-in": "fadeIn 0.5s ease forwards",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 10px rgba(0,200,150,0.3)" },
          "50%": { opacity: "0.7", boxShadow: "0 0 20px rgba(0,200,150,0.6)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "100% 0" },
          "100%": { backgroundPosition: "-100% 0" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(8px)", filter: "blur(4px)" },
          to: { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
